[package]
name = "asundeer"
version = "0.1.0"
authors = ["Kaura Peura <kaura.peura@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
